server:
  port: 8080

app:
  client:
    base-url: https://j11a301.p.ssafy.io
  oauth:
    base-url: https://j11a301.p.ssafy.io

spring:
  docker:
    compose:
      enabled: off

  datasource:
    url: jdbc:mariadb://mariadb:3306/newsseug?serverTimezone=Asia/Seoul
    username: root
    password: newsseug1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: redis
      port: 6379

    elasticsearch:
      url: es:9200
      repositories:
        enabled: true