app:
  oauth:
    base-url: http://localhost:8080

spring:
  application:
    name: newsseug

  profiles:
    default: local

  config:
    import: application-jwt.yml, application-oauth.yml

  data:
    redis:
      host: localhost
      port: 6379