server:
  port: 8080

spring:

  docker:
    compose:
      enabled: off

  datasource:
    url: jdbc:mariadb://localhost:3306/newsseug?serverTimezone=Asia/Seoul
    username: root
    password: newsseug1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

