services:

  mariadb:
    image: 'mariadb:11.5.2'
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Seoul
      MYSQL_USER: newsseug
      MYSQL_DATABASE: newsseug
      MYSQL_PASSWORD: newsseug1234
      MARIADB_ROOT_PASSWORD: newsseug1234
    volumes:
      - mydata:/var/lib/mysql
    restart: on-failure
    networks:
      - newsseug-network

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    environment:
      TZ: Asia/Seoul
    volumes:
      - redisdata:/data
    restart: on-failure
    networks:
      - newsseug-network

  newsseug-backend:
    container_name: newsseug-backend
    build: ./backend/newsseug
    image: newsseug-backend
    depends_on:
      - mariadb
      - redis
    environment:
      - TZ=Asia/Seoul
    ports:
      - '8080:8080'
    restart: always
    networks:
      - newsseug-network

volumes:
  mydata:
  redisdata:

networks:
  newsseug-network: