services:

  mariadb:
    container_name: mariadb
    image: 'mariadb:11.5.2'
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_USER: newsseug
      MYSQL_DATABASE: newsseug
      MYSQL_PASSWORD: newsseug1234
      MARIADB_ROOT_PASSWORD: newsseug1234
    volumes:
      - /home/ubuntu/volume/mysql-data:/var/lib/mysql
    restart: on-failure
    networks:
      - newsseug-network

  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Seoul
    volumes:
      - /home/ubuntu/volume/redis-data:/data
    restart: on-failure
    networks:
      - newsseug-network

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: es
    environment:
      - node.name=es-node
      - cluster.name=search-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - newsseug-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - newsseug-network

  prometheus:
    user: root
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - newsseug-backend
    volumes:
      - /var/jenkins_home/workspace/newsseug-server/backend/newsseug/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/ubuntu/volume/prometheus-data:/var/lib/prometheus
    ports:
      - 9000:9090
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      - newsseug-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - newsseug-backend
    ports:
      - 3030:3000
    volumes:
      - /home/ubuntu/volume/grafana-data:/var/lib/grafana
    networks:
      - newsseug-network

  newsseug-backend:
    image: newsseug-backend
    container_name: newsseug-backend
    depends_on:
      - mariadb
      - redis
      - es
    environment:
      - TZ=Asia/Seoul
    ports:
      - 8080:8080
    restart: always
    networks:
      - newsseug-network

networks:
  newsseug-network:
      driver: bridge